# Generated by Django 5.2.3 on 2025-06-28 11:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        help_text="e.g., Double bed(s), Extra-large double bed(s)",
                        max_length=255,
                    ),
                ),
                (
                    "size",
                    models.CharField(help_text="e.g., 131-150 cm wide", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Bed Type",
                "verbose_name_plural": "Bed Types",
                "ordering": ["type"],
            },
        ),
        migrations.CreateModel(
            name="RoomAmenity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Room Amenity",
                "verbose_name_plural": "Room Amenities",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "size",
                    models.IntegerField(
                        help_text="Room size in square meters/feet",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="m2",
                        help_text="Unit of measurement (m2, ft2)",
                        max_length=10,
                    ),
                ),
                (
                    "adults",
                    models.IntegerField(
                        help_text="Maximum adults",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "children",
                    models.IntegerField(
                        help_text="Maximum children",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "occupancy",
                    models.IntegerField(
                        help_text="Total occupancy",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotels.hotel",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="rooms", to="rooms.roomamenity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["hotel", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("main_photo", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Image",
                "verbose_name_plural": "Room Images",
                "ordering": ["-main_photo", "-score", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomBedType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "bed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.bedtype"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bed_types",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Bed Type",
                "verbose_name_plural": "Room Bed Types",
                "unique_together": {("room", "bed_type")},
            },
        ),
    ]
