# Generated by Django 5.2.3 on 2025-06-28 11:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("facilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("main_photo", models.URLField(blank=True, max_length=500, null=True)),
                ("thumbnail", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("address", models.TextField()),
                (
                    "address_suburb",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stars",
                    models.IntegerField(
                        help_text="Hotel star rating (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hotel rating (0-10)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("ranking", models.IntegerField(default=0)),
                ("reviews_count", models.IntegerField(default=0)),
                ("best_seller", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotels",
                        to="core.hotelchain",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="core.city",
                    ),
                ),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True, related_name="hotels", to="facilities.facility"
                    ),
                ),
                (
                    "hotel_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotels",
                        to="core.hoteltype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Host who owns this hotel",
                        limit_choices_to={"role": "host"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_hotels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hotels",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                ("url_hd", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.IntegerField(default=1)),
                ("default_image", models.BooleanField(default=False)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Image",
                "verbose_name_plural": "Hotel Images",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
